project:
  type: website

website:
  title: "e-prospectiva"
  site-url: https://e-prospectiva.netlify.app/
  repo-url: https://github.com/carlosgino/e-prospectiva
  favicon: images/logo.png
  open-graph:
        locale: es_ES
        site-name: Quarto
  repo-actions: [edit, issue]
  comments:
    utterances:
      repo: carlosgino/e-prospectiva
      label: "Comments"
  twitter-card:
    creator: "@g_garibotto"
    card-style: summary_large_image
  navbar:
    background: "green"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/carlosgino
      - icon: rss
        href: index.xml
      - icon: linkedin
        href: https://www.linkedin.com/in/carlos-gino-garibotto-sandoval-8968744b/
      - icon: twitter
        href: https://twitter.com/g_garibotto
      - icon: facebook
        href: https://www.facebook.com/carlosgaribottosandoval
format:
   html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    highlight-style: eiffel
    editor: source

    page-footer:
    left: "2022 Gino Garibotto"
    right: |
      Made with ♥ using `{Quarto}`citation: true
    license: "CC BY"
    include-after-body: footer.html
    execute:
      freeze: auto